#!/bin/bash

workspace=$1
last_workspace_file="$HOME/.cache/last_workspace"

if [ ! -f "$last_workspace_file" ]; then
  echo "No last workspace file found."
  exit 1
fi

current_workspace=$(bspc query -T --desktop | jq -r '.name')

if [ "$current_workspace" = "$workspace" ]; then
    bspc desktop -f "$(cat "$last_workspace_file")"
else
  if [ "$current_workspace" != "9" ] && [ "$current_workspace" != "8" ]; then
    echo "$current_workspace" > "$last_workspace_file"
  fi
  bspc desktop -f "$workspace"
fi
