#!/bin/bash

TERMINAL_PID=$(xdotool getwindowfocus getwindowpid)
TERMINAL_ID=$(xdotool getactivewindow)

zathura "$1" &
ZATHURA_PID=$!

xdo hide "$TERMINAL_ID"
wait "$ZATHURA_PID"
xdo show "$TERMINAL_ID"
